stages:
  - build
  - deploy

build_all:
  image: node:latest
  stage: build
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - _site

pages:
  stage: deploy
  script:
    - mv _site public
  artifacts:
    paths:
    - public
