[build]
	command = "npm run build"
	publish = "_site"

[[context.production.plugins]]
	package = "/plugins/send_webmentions"

[[redirects]]
	from = "/.well-known/host-meta*"
	to = "https://fed.brid.gy/.well-known/host-meta:splat"
	status = 302
[[redirects]]
	from = "/.well-known/webfinger*"
	to = "https://fed.brid.gy/.well-known/webfinger"
	status = 302

[template.environment]
	BASE_URL = "The base URL for this site"
	SHORT_URL = "A short URL to be used as a permalink"
	EMAIL = "Email address. Currently only used in *.xml"

# https://docs.netlify.com/routing/headers/
# Can also be added in `_headers`
[[headers]]
  for = "/*"
  [headers.values]
    X-Clacks-Overhead = '''
    GNU Terry Pratchett,
    David Bowie,
    Carrie Fisher,
    Satoru Iwata,
    Aaron Swartz'''
