name: Eleventy Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Initialize .env
      run: |
        touch .env
        echo URL=${{ secrets.ENV_URL }} >> .env
        echo SHORT_URL=${{ secrets.ENV_SHORT_URL }} >> .env

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm ci
    - run: npm run build

    - name: Deploy GH Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site

    - name: Upload
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        source: "./_site/*"
        strip_components: 1
        target: "${{ secrets.SERVER_TARGET }}"
