name: Fetch webmentions

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  fetch_webmentions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          # https://github.com/orgs/community/discussions/25702
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Fetch webmentions
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          SHORT_URL: ${{ secrets.SHORT_URL }}
          WEBMENTION_IO_TOKEN: ${{ secrets.WEBMENTION_IO_TOKEN }}
        run: node ./plugins/fetch_webmentions.js

      - name: Commit webmentions
        id: wm_commit
        run: |
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git add wm
          # https://stackoverflow.com/a/3162492
          count=($(git diff --cached --numstat | wc -l))
          count=$((count-1)) # Subtract 1 since this would include cache file
          # https://stackoverflow.com/a/40255467
          git diff --quiet && git diff --staged --quiet || (git commit -am "webmentions: adding ($count) webmentions"; git push;)
