name: Backup webmentions

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  backup_webmentions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # https://github.com/orgs/community/discussions/25702
          # GITHUB_TOKEN does trigger a Netlify deploy
          # Will need to switch to PAT if switching to GitHub deploy
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Backup webmentions
        env:
          WM_TOKEN: ${{ secrets.WM_TOKEN }}
        run: node ./plugins/fetch_webmentions.js

      - name: Commit webmentions
        id: wm_commit
        run: |
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git add wm
          # https://stackoverflow.com/a/40255467
          git diff --quiet && git diff --staged --quiet || (git commit -am "webmentions: updating backup"; git push;)
