name: Send Webmentions

on:
  workflow_run:
    workflows: ["Eleventy Build"]
    types:
      - completed

jobs:
  send_webmentions:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check cache
        if: ${{ !env.ACT }}
        uses: actions/cache@v3
        with:
          path: .webmentions.cache
          key: webmentions

      - name: Send Webmentions
        env:
          JSON_FEED: ${{ secrets.JSON_FEED }}
          CACHE_FILE: ${{ secrets.CACHE_FILE || '.webmentions.cache' }}
          LIMIT: 10
          DEBUG: ${{ secrets.DEBUG }}
        shell: bash
        run: |
          debug() { [ "$DEBUG" = true ] && echo "[DEBUG] $1" || true; }

          [[ "$DEBUG" = "true" ]] && METHOD="GET" || METHOD="POST"
          [ -z "$LATEST" ] && LIMIT=1 && debug "Cache doesn't exist. Set LIMIT=1"
          [ -f "$CACHE_FILE" ] && LATEST=$(<$CACHE_FILE) && debug "Found cache. Latest checked item: $LATEST"

          FEED=$(curl --silent -L "$JSON_FEED")

          i=0
          while read -r item; do
            [ -z "$NEWEST" ] && debug "Set newest to $item" && NEWEST="$item"
            [ "$i" -ge "$LIMIT" ] && debug "Reached limit. Breaking" && break
            [ "$item" = "$LATEST" ] && debug "Current item matched latest checked. Breaking" && break
            i=$((i+1))
            debug "Should check $item with $METHOD"
            curl -X $METHOD https://webmention.app/check?url="${item}"
          done < <(echo "${FEED}" | jq -r '.items[].id')

          if [ "$NEWEST" != "$LATEST" ]; then
            debug "Writing $NEWEST to $CACHE_FILE"
            echo "$NEWEST" > $CACHE_FILE
          fi

      - name: Cache webmentions
        if: ${{ !env.ACT }}
        uses: actions/cache@v3
        with:
          path: .webmentions.cache
          key: webmentions
