name: Webmentions

on:
  workflow_call:

jobs:
  webmentions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get cached node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}

    - name: Get cached site
      uses: actions/cache@v2
      with:
        path: |
          .env
          _site
          feed.html
        key: ${{ runner.os }}-site-${{ github.sha }}

    - name: Send Webmentions
      continue-on-error: true
      run: node webmentions.js
